# Generated by Django 3.0 on 2022-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trackedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
