# Generated by Django 3.0 on 2022-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membership_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='usage_record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
